services:
  car_db:
    image: postgres:16
    container_name: car_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myst1
      POSTGRES_PASSWORD: coxinha123
      POSTGRES_DB: car_rental
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - car-network

  redis:
    image: redis:7
    container_name: redis_auth
    ports:
      - "6379:6379"
    networks:
      - car-network

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "4003:4001"
    depends_on:
      - car_db
      - redis
    environment:
      - DATABASE_URL=postgres://myst1:coxinha123@car_db:5432/car_rental
      - REDIS_URL=redis://redis_auth:6379
    networks:
      - car-network

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "4002:4002"
    depends_on:
      - car_db
    environment:
      - DATABASE_URL=postgres://myst1:coxinha123@car_db:5432/car_rental
      - REDIS_URL=redis://redis_auth:6379
    networks:
      - car-network

  car-service:
    build:
      context: ./car-service
    container_name: car-service
    ports:
      - "4004:4003"
    depends_on:
      - car_db
    environment:
      - DATABASE_URL=postgres://myst1:coxinha123@car_db:5432/car_rental
      - REDIS_URL=redis://redis_auth:6379
    networks:
      - car-network

  blog-service:
    build:
      context: ./blog-service
    container_name: blog-service
    ports:
      - "4005:4005"
    depends_on:
      - car_db
    environment:
      - DATABASE_URL=postgres://myst1:coxinha123@car_db:5432/car_rental
      - REDIS_URL=redis://redis_auth:6379
    networks:
      - car-network

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "4000:4000"
    environment:
      - REDIS_URL=redis://redis_auth:6379
      - IDENTITY_SERVICE_URL=http://auth-service:4001
    depends_on:
      - auth-service
      - redis
    networks:
      - car-network

volumes:
  db-data:

networks:
  car-network:
    driver: bridge